### ISSUE TITLE
How can I use blotnet in my research?

### ISSUE THREAD

**Issue by dataplayer12** [apple2373/western_recognize#1]
Hi, I came across your publication. This is quite great work. I would like to know if your network can be used for performing western blot analysis by replacing the conventional method? What advantages of deep learning do you envisage for western blot analysis?

**Comment by apple2373** [comment]
Thanks for the interest! Sorry, I am afraid that my method CANNOT really analyze western blot.... This is a very simple binary classification method to tell if a given image is western blot or not. Extracting more meanings from the plot is much more difficult, which I haven't tried.

**Comment by dataplayer12** [comment]
Thanks for the clarification. I understand.
